baseURL = "https://meghaphone.github.io/"
languageCode = "en-us"
title = "Meghan Kane"
theme = "hugo-creative-portfolio-theme"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = "internet corner of meghan kane"
  sidebarAbout = [
    "ğŸ™‹ğŸ¼ Hey! I'm Meghan. I am a software developer focusing on iOS app development. I like creating software that can make the world a little bit better each day. ğŸŒğŸ’œ Back in the day, I studied Computer Science & Math @ MIT ğŸ‘©ğŸ¼â€ğŸ“",
    "ğŸ‘©ğŸ¼â€ğŸ« I subscribe to a life long learning approach, so I'm continuously researching new areas that can better the software I create. My current research focus is machine learning for iOS apps.",
    "Some things I like are ğŸš², â˜•ï¸, ğŸ“š, and using too many emoji. ğŸ™ƒ",	
    "Thanks for stopping by! Feel free to reach out to connect ğŸ‘‡",
    ""
  ]

  # Nav links in the side bar
 #  [[params.navlinks]]
 # name = "Home"
 # url = ""

  [params.social]
  email         = "kanemeghan@gmail.com"
  twitter       = "https://www.twitter.com/meghafon"
  github        = "https://www.github.com/meghaphone"
  linkedin      = "https://www.linkedin.com/in/meghaphone/"