baseURL = "https://meghaphone.github.io/"
languageCode = "en-us"
title = "Meghan Kane"
theme = "hugo-creative-portfolio-theme"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = "internet corner of meghan kane"
  sidebarAbout = [
    "ğŸ™‹ğŸ¼â€â™€ï¸ Hey! I'm a software developer & I also study topics in the realm of computational science. After studying Math & CS @ MIT, the 1st stage - tool building stage - of my career was spent working across the stack. Next stage will be to use these tools to find ways to contribute to problems in applied science.",
    "ğŸ•µğŸ¼ For insight into my other intellectual curiosities, check my /about page ğŸ‘‡. I also love biking, funk music, taking spaziergÃ¤nge (strolls), & discussing ideas with people across the ideological spectrum.",
    "NOTE: portfolio work is out of date. Check back for updates."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  email         = "kanemeghan@gmail.com"
  twitter       = "https://www.twitter.com/meghafon"
  github        = "https://www.github.com/meghaphone"
  linkedin      = "https://www.linkedin.com/in/meghaphone/"