baseURL = "https://meghaphone.github.io/"
languageCode = "en-us"
title = "Meghan Kane"
theme = "hugo-creative-portfolio-theme"

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "pink"
  description = "internet corner of meghan kane"
  sidebarAbout = [
    "ğŸ™‹ğŸ¼â€â™€ï¸ Hey! I'm a software developer based primarily in Berlin & I also study problems traditionally categorized under computational science. After studying Math & CS @ MIT, the 1st stage - tool building stage - of my career was spent working across the stack.",
    "ğŸ‘©ğŸ¼â€ğŸ”¬ Next stage will be to use these tools to contribute to problems in applied science. Note: work featured ğŸ‘‰ is outdated. Check back soon for current work & musings.",
    "ğŸ•µğŸ¼â€ For insight into my other intellectual curiosities, check my About page",
    "ğŸ¤¸ğŸ¼â€â™€ï¸ I also love biking, funk music, taking spaziergÃ¤nge (strolls), and discussing ideas with people across the ideological spectrum."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  email         = "kanemeghan@gmail.com"
  twitter       = "https://www.twitter.com/meghafon"
  github        = "https://www.github.com/meghaphone"
  linkedin      = "https://www.linkedin.com/in/meghaphone/"